# Setup
title:               Memories
tagline:             'Sometimes you will never know the value of a moment, until it becomes a memory.'
description:         'Work in progress'
url:                 https://dewei84.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
show_excerpts: true
excerpt_separator: <!--more-->

# About/contact
author:
  name:              Lin Dewei
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
